# Generated by Django 4.0 on 2021-12-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
